In [2]:

import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [3]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

import nltk
import string
import numpy as np
nltk.download('stopwords')
nltk.download('punkt')
stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [5]:
data= pd.read_csv("/spam (1).csv",encoding = "ISO-8859-1")
data= data.drop(data.columns[[2,3,4]],axis=1)
data


v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [6]:
filtered_data=[]
for text in data['v2']:
  text = text.translate(str.maketrans('', '', string.punctuation))
  word_tokens = word_tokenize(text)
  sentence = [w for w in word_tokens if not w.lower() in stop_words]
  s= ' '.join(sentence)
  filtered_data.append(s)

filtered_data= np.array(filtered_data)
filtered_data= filtered_data.reshape(-1,1)

data["filtered"]= filtered_data
print(data)

        v1                                                 v2  \
0      ham  Go until jurong point, crazy.. Available only ...   
1      ham                      Ok lar... Joking wif u oni...   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...   
3      ham  U dun say so early hor... U c already then say...   
4      ham  Nah I don't think he goes to usf, he lives aro...   
...    ...                                                ...   
5567  spam  This is the 2nd time we have tried 2 contact u...   
5568   ham              Will Ì_ b going to esplanade fr home?   
5569   ham  Pity, * was in mood for that. So...any other s...   
5570   ham  The guy did some bitching but I acted like i'd...   
5571   ham                         Rofl. Its true to its name   

                                               filtered  
0     Go jurong point crazy Available bugis n great ...  
1                               Ok lar Joking wif u oni  
2     Free entry 2 wkly comp win FA Cup final

In [7]:
data_train,data_test= train_test_split(data[["filtered"]],test_size=0.2)

In [11]:
enc = TfidfVectorizer()
x= enc.fit_transform(data["filtered"])
# print(x.shape)
# y= enc.fit_transform([data["v1"]]).reshape(-1,1)
# print(y.shape)
x_train,x_test,y_train,y_test= train_test_split(x.toarray(),data['v1'],test_size=0.2)
regr= LogisticRegression()
print(x_train)
regr.fit(x_train,y_train)
# regr.score(x_test,y_test)
text= [" Phony å£350 award - Todays Voda nu quoting claim code 3100 standard rates app"]
# text.reshape(-1, 1)
vector= enc.transform(text)
ham_proba, spam_proba = regr.predict_proba(vector).squeeze()
print("ham") if ham_proba>.75 else print("spam")


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
ham


In [12]:
enc = CountVectorizer(stop_words='english').fit_transform(data['v2'])
x.shape
x_train,x_test,y_train,y_test= train_test_split(x,data[['v1']],test_size=0.2)
regr= LogisticRegression()
regr.fit(x_train,y_train)
regr.score(x_test,y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9479820627802691

In [13]:
enc = TfidfVectorizer(stop_words='english').fit_transform(data['v2'])
x.shape
x_train,x_test,y_train,y_test= train_test_split(x,data[['v1']],test_size=0.2)
regr= LogisticRegression()
regr.fit(x_train,y_train)
regr.score(x_test,y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9479820627802691